//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2020 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/aws/aws-sdk-go-v2/service/s3/types"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DOSpace) DeepCopyInto(out *DOSpace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DOSpace.
func (in *DOSpace) DeepCopy() *DOSpace {
	if in == nil {
		return nil
	}
	out := new(DOSpace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DOSpace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DOSpaceList) DeepCopyInto(out *DOSpaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DOSpace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DOSpaceList.
func (in *DOSpaceList) DeepCopy() *DOSpaceList {
	if in == nil {
		return nil
	}
	out := new(DOSpaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DOSpaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DOSpaceObservation) DeepCopyInto(out *DOSpaceObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DOSpaceObservation.
func (in *DOSpaceObservation) DeepCopy() *DOSpaceObservation {
	if in == nil {
		return nil
	}
	out := new(DOSpaceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DOSpaceParameters) DeepCopyInto(out *DOSpaceParameters) {
	*out = *in
	if in.ACL != nil {
		in, out := &in.ACL, &out.ACL
		*out = new(string)
		**out = **in
	}
	if in.GrantFullControl != nil {
		in, out := &in.GrantFullControl, &out.GrantFullControl
		*out = new(string)
		**out = **in
	}
	if in.GrantRead != nil {
		in, out := &in.GrantRead, &out.GrantRead
		*out = new(string)
		**out = **in
	}
	if in.GrantReadACP != nil {
		in, out := &in.GrantReadACP, &out.GrantReadACP
		*out = new(string)
		**out = **in
	}
	if in.GrantWrite != nil {
		in, out := &in.GrantWrite, &out.GrantWrite
		*out = new(string)
		**out = **in
	}
	if in.GrantWriteACP != nil {
		in, out := &in.GrantWriteACP, &out.GrantWriteACP
		*out = new(string)
		**out = **in
	}
	if in.ObjectOwnership != nil {
		in, out := &in.ObjectOwnership, &out.ObjectOwnership
		*out = new(types.ObjectOwnership)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DOSpaceParameters.
func (in *DOSpaceParameters) DeepCopy() *DOSpaceParameters {
	if in == nil {
		return nil
	}
	out := new(DOSpaceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DOSpaceSpec) DeepCopyInto(out *DOSpaceSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DOSpaceSpec.
func (in *DOSpaceSpec) DeepCopy() *DOSpaceSpec {
	if in == nil {
		return nil
	}
	out := new(DOSpaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DOSpaceStatus) DeepCopyInto(out *DOSpaceStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DOSpaceStatus.
func (in *DOSpaceStatus) DeepCopy() *DOSpaceStatus {
	if in == nil {
		return nil
	}
	out := new(DOSpaceStatus)
	in.DeepCopyInto(out)
	return out
}
