apiVersion: compute.do.crossplane.io/v1alpha1
kind: Droplet
metadata:
  name: user-data-example
spec:
  forProvider:
    region: nyc1
    size: s-1vcpu-1gb
    image: ubuntu-20-04-x64
    userData: |
      #!/bin/bash
      apt-get -y update
      apt-get -y install nginx
      export HOSTNAME=$(curl -s http://169.254.169.254/metadata/v1/hostname)
      export PUBLIC_IPV4=$(curl -s http://169.254.169.254/metadata/v1/interfaces/public/0/ipv4/address)
      echo Droplet: $HOSTNAME, IP Address: $PUBLIC_IPV4 > /var/www/html/index.html
  providerConfigRef:
    name: example
